version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - php
      - mysql
  php:
    image: php-pdo
    user: "www-data:www-data"
    volumes:
      - ./app:/var/www/app
    restart: always

  mysql:
    image: mysql
    restart: always
    container_name: mysql-container
    volumes:
      - ./data/db:/var/lib/mysql
      - ./data/db-init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=users_auth
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=authuser
      - MYSQL_PASSWORD=passAuth123
    ports:
      - "8989:3306"

networks:
  code-network:
    driver: bridge
